/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */

import {
  Kind,
  SchemaOptions,
  Static,
  TSchema,
  TUnion,
  Type,
  TypeRegistry,
} from "@sinclair/typebox";
import { Value } from "@sinclair/typebox/value";

export const Module = Type.Module({
  RecursiveType: Type.Object(
    {
      label: Type.Optional(Type.Union([Type.Number()])),
      value: Type.Optional(Type.Ref("RecursiveType")),
    },
    {
      $id: "recursive.json",
      $schema: "https://json-schema.org/draft/2020-12/schema",
    }
  )
});
export const RecursiveType = Module.Import("RecursiveType");
export type RecursiveType = Static<typeof RecursiveType>;
